version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - typescript-express-template/db.env
    ports:
      - "2345:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  express:
    build:
      context: typescript-express-template
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - typescript-express-template/.env
    depends_on:
      - postgres
